packages:
  - "packages/*"
  - "apps/*"
  - "examples/*"
  - "examples/micro-service/*"
  - "tools/*"

allowBuilds:
  '@prisma/engines': set this to true or false
  better-sqlite3: true
  esbuild: set this to true or false
  prisma: set this to true or false

catalog:
  typescript: ^7.0.2
  "@types/node": ^26.4.0
