/**
 * @zudo/openapi/openApiConstants
 */

export {
  DEFAULT_OPENAPI_VERSION,
  MAX_OPERATION_ID_LENGTH,
  COMPONENT_REF_PREFIX,
  DEFAULT_MEDIA_TYPE,
  STATUS_CODE_CATEGORIES,
  DEFAULT_SERVER_URL,
  DOCUMENT_CACHE_TTL_MS,
} from "./openApiConstants.core.js";
