/**
 * Standard error codes used across the Lattice platform.
 *
 * Codes are intentionally stable because they may be consumed by
 * APIs, clients, logs, monitoring systems, and external integrations.
 */
export enum ErrorCode {
  UNKNOWN = "ERR_UNKNOWN",

  INTERNAL = "ERR_INTERNAL",
  NOT_IMPLEMENTED = "ERR_NOT_IMPLEMENTED",
  SERVICE_UNAVAILABLE = "ERR_SERVICE_UNAVAILABLE",

  INVALID_INPUT = "ERR_INVALID_INPUT",
  VALIDATION_FAILED = "ERR_VALIDATION_FAILED",
  INVALID_FORMAT = "ERR_INVALID_FORMAT",
  INVALID_VALUE = "ERR_INVALID_VALUE",
  MISSING_FIELD = "ERR_MISSING_FIELD",
  INVALID_FIELD = "ERR_INVALID_FIELD",

  UNAUTHORIZED = "ERR_UNAUTHORIZED",
  FORBIDDEN = "ERR_FORBIDDEN",
  ACCESS_DENIED = "ERR_ACCESS_DENIED",

  NOT_FOUND = "ERR_NOT_FOUND",
  RESOURCE_NOT_FOUND = "ERR_RESOURCE_NOT_FOUND",
  ROUTE_NOT_FOUND = "ERR_ROUTE_NOT_FOUND",

  CONFLICT = "ERR_CONFLICT",
  ALREADY_EXISTS = "ERR_ALREADY_EXISTS",
  DUPLICATE = "ERR_DUPLICATE",

  RATE_LIMITED = "ERR_RATE_LIMITED",
  TOO_MANY_REQUESTS = "ERR_TOO_MANY_REQUESTS",

  TIMEOUT = "ERR_TIMEOUT",
  REQUEST_TIMEOUT = "ERR_REQUEST_TIMEOUT",

  NETWORK = "ERR_NETWORK",
  CONNECTION_FAILED = "ERR_CONNECTION_FAILED",

  DATABASE = "ERR_DATABASE",
  DATABASE_CONNECTION = "ERR_DATABASE_CONNECTION",
  DATABASE_QUERY = "ERR_DATABASE_QUERY",
  DATABASE_TRANSACTION = "ERR_DATABASE_TRANSACTION",

  CONFIGURATION = "ERR_CONFIGURATION",
  CONFIGURATION_MISSING = "ERR_CONFIGURATION_MISSING",
  CONFIGURATION_INVALID = "ERR_CONFIGURATION_INVALID",

  AUTHENTICATION = "ERR_AUTHENTICATION",
  AUTHENTICATION_FAILED = "ERR_AUTHENTICATION_FAILED",
  INVALID_CREDENTIALS = "ERR_INVALID_CREDENTIALS",
  SESSION_EXPIRED = "ERR_SESSION_EXPIRED",
  TOKEN_INVALID = "ERR_TOKEN_INVALID",
  TOKEN_EXPIRED = "ERR_TOKEN_EXPIRED",

  CRYPTO = "ERR_CRYPTO",
  CRYPTO_KEY = "ERR_CRYPTO_KEY",
  CRYPTO_HASH = "ERR_CRYPTO_HASH",
  CRYPTO_CIPHER = "ERR_CRYPTO_CIPHER",
  CRYPTO_SIGNATURE = "ERR_CRYPTO_SIGNATURE",
  CRYPTO_DERIVATION = "ERR_CRYPTO_DERIVATION",

  EXTERNAL_SERVICE = "ERR_EXTERNAL_SERVICE",
  EXTERNAL_SERVICE_TIMEOUT = "ERR_EXTERNAL_SERVICE_TIMEOUT",
  EXTERNAL_SERVICE_UNAVAILABLE = "ERR_EXTERNAL_SERVICE_UNAVAILABLE",

  FILE = "ERR_FILE",
  FILE_NOT_FOUND = "ERR_FILE_NOT_FOUND",
  FILE_READ = "ERR_FILE_READ",
  FILE_WRITE = "ERR_FILE_WRITE",
  FILE_UPLOAD = "ERR_FILE_UPLOAD",
  FILE_DOWNLOAD = "ERR_FILE_DOWNLOAD",

  PERMISSION = "ERR_PERMISSION",
  RESOURCE_LOCKED = "ERR_RESOURCE_LOCKED",

  OPERATION_FAILED = "ERR_OPERATION_FAILED",
  OPERATION_CANCELLED = "ERR_OPERATION_CANCELLED",
  PRECONDITION_FAILED = "ERR_PRECONDITION_FAILED",

  INTERNAL_ERROR = "ERR_INTERNAL_ERROR",
  SYSTEM_ERROR = "ERR_SYSTEM_ERROR",
  SYSTEM_INITIALIZATION = "ERR_SYSTEM_INITIALIZATION",
  SYSTEM_STARTUP = "ERR_SYSTEM_STARTUP",
  SYSTEM_SHUTDOWN = "ERR_SYSTEM_SHUTDOWN",
  SERVICE_ERROR = "ERR_SERVICE_ERROR",
  SERVICE_INITIALIZATION = "ERR_SERVICE_INITIALIZATION",
  SERVICE_OPERATION = "ERR_SERVICE_OPERATION",
  STORAGE = "ERR_STORAGE",
  STORAGE_READ = "ERR_STORAGE_READ",
  STORAGE_WRITE = "ERR_STORAGE_WRITE",
  STORAGE_UPLOAD = "ERR_STORAGE_UPLOAD",
  STORAGE_DOWNLOAD = "ERR_STORAGE_DOWNLOAD",
  STORAGE_DELETE = "ERR_STORAGE_DELETE",
  STORAGE_NOT_FOUND = "ERR_STORAGE_NOT_FOUND",
  DATABASE_TIMEOUT = "ERR_DATABASE_TIMEOUT",
  LOCK_TIMEOUT = "ERR_LOCK_TIMEOUT",

  // CQRS
  COMMAND_HANDLER_NOT_FOUND = "ERR_COMMAND_HANDLER_NOT_FOUND",
  QUERY_HANDLER_NOT_FOUND = "ERR_QUERY_HANDLER_NOT_FOUND",
  INVALID_COMMAND = "ERR_INVALID_COMMAND",
  INVALID_QUERY = "ERR_INVALID_QUERY",
  EVENT_HANDLER_FAILED = "ERR_EVENT_HANDLER_FAILED",
  CONFIGURATION_ERROR = "ERR_CONFIGURATION_ERROR",
}

/**
 * Determines whether a value is a valid Lattice error code.
 */
export function isErrorCode(
  value: unknown,
): value is ErrorCode {
  return (
    typeof value === "string" &&
    Object.values(ErrorCode).includes(
      value as ErrorCode,
    )
  );
}

/**
 * Converts an unknown value into a valid error code.
 */
export function normalizeErrorCode(
  value: unknown,
): ErrorCode {
  if (isErrorCode(value)) {
    return value;
  }

  return ErrorCode.UNKNOWN;
}